name = "db_pool"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
repository = { type = "github", user = "stndrs", repo = "db_pool" }
target = "erlang"

internal_modules = [
  "db/pool/internal/*"
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
global_value = ">= 1.0.0 and < 2.0.0"
exception = ">= 2.1.0 and < 3.0.0"
