name = "db_pool"
version = "1.0.0"

description = "A database connection pool"
licences = ["MIT"]
repository = { type = "github", user = "stndrs", repo = "db_pool" }
target = "erlang"

internal_modules = [
  "db_pool/internal/*",
  "db_pool/internal"
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
global_value = ">= 1.0.0 and < 2.0.0"
exception = ">= 2.1.0 and < 3.0.0"
